/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fmservice_server_fminterface_proxy_FaceFinderProxy */

#ifndef _Included_fmservice_server_fminterface_proxy_FaceFinderProxy
#define _Included_fmservice_server_fminterface_proxy_FaceFinderProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fmservice_server_fminterface_proxy_FaceFinderProxy
 * Method:    n_FaceFinderCreate
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_fmservice_server_fminterface_proxy_FaceFinderProxy_n_1FaceFinderCreate
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jint);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceFinderProxy
 * Method:    n_gotFaces
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_fmservice_server_fminterface_proxy_FaceFinderProxy_n_1gotFaces
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceFinderProxy
 * Method:    n_getFaces
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fmservice_server_fminterface_proxy_FaceFinderProxy_n_1getFaces
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceFinderProxy
 * Method:    n_getErrorMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fmservice_server_fminterface_proxy_FaceFinderProxy_n_1getErrorMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceFinderProxy
 * Method:    n_setVerboseLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fmservice_server_fminterface_proxy_FaceFinderProxy_n_1setVerboseLevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
