/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fmservice_server_fminterface_proxy_FaceRegionMatcherProxy */

#ifndef _Included_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
#define _Included_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_createImageMatcher
 * Signature: (JLjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1createImageMatcher
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_ingestRegion
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1ingestRegion
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_clearIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1clearIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_loadIndexData
 * Signature: (J[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1loadIndexData
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_loadIndexFiles
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1loadIndexFiles
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_loadMasterIndexFile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1loadMasterIndexFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_saveIndexData
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1saveIndexData
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_removeRegions
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1removeRegions
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_queryMatches
 * Signature: (JLjava/lang/String;[Ljava/lang/String;F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1queryMatches
  (JNIEnv *, jclass, jlong, jstring, jobjectArray, jfloat);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_getErrorMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1getErrorMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fmservice_server_fminterface_proxy_FaceRegionMatcherProxy
 * Method:    n_setVerboseLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fmservice_server_fminterface_proxy_FaceRegionMatcherProxy_n_1setVerboseLevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
