/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fmservice_server_fminterface_proxy_InfoProxy */

#ifndef _Included_fmservice_server_fminterface_proxy_InfoProxy
#define _Included_fmservice_server_fminterface_proxy_InfoProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fmservice_server_fminterface_proxy_InfoProxy
 * Method:    n_getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fmservice_server_fminterface_proxy_InfoProxy_n_1getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
