/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fmservice_server_fminterface_proxy_FRDProxy */

#ifndef _Included_fmservice_server_fminterface_proxy_FRDProxy
#define _Included_fmservice_server_fminterface_proxy_FRDProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fmservice_server_fminterface_proxy_FRDProxy
 * Method:    n_createSimpleFRD
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIDDDZ)J
 */
JNIEXPORT jlong JNICALL Java_fmservice_server_fminterface_proxy_FRDProxy_n_1createSimpleFRD
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jint, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     fmservice_server_fminterface_proxy_FRDProxy
 * Method:    n_createFRDWithLock
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIDDDZ)J
 */
JNIEXPORT jlong JNICALL Java_fmservice_server_fminterface_proxy_FRDProxy_n_1createFRDWithLock
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jint, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     fmservice_server_fminterface_proxy_FRDProxy
 * Method:    n_usingGPU
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_fmservice_server_fminterface_proxy_FRDProxy_n_1usingGPU
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fmservice_server_fminterface_proxy_FRDProxy
 * Method:    n_deallocate
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_fmservice_server_fminterface_proxy_FRDProxy_n_1deallocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fmservice_server_fminterface_proxy_FRDProxy
 * Method:    n_getErrorMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fmservice_server_fminterface_proxy_FRDProxy_n_1getErrorMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fmservice_server_fminterface_proxy_FRDProxy
 * Method:    n_setVerboseLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fmservice_server_fminterface_proxy_FRDProxy_n_1setVerboseLevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
